/simple_erob_control:
  ros__parameters:

    can_interface: "can0"

    num_motors: 7

    motor_names: ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6", "joint7"]

    joint1:
      node_id: 1
      operation_mode: "PPM"
      max_velocity: 5.0
      max_torque: 2.0
      
    joint2:
      node_id: 2
      operation_mode: "PPM"
      max_velocity: 5.0
      max_torque: 2.0
      
    joint3:
      node_id: 3
      operation_mode: "PPM"
      max_velocity: 5.0
      max_torque: 2.0
      
    joint4:
      node_id: 4
      operation_mode: "PPM"
      max_velocity: 5.0
      max_torque: 2.0
      
    joint5:
      node_id: 5
      operation_mode: "PPM"
      max_velocity: 5.0
      max_torque: 2.0
      
    joint6:
      node_id: 6
      operation_mode: "PPM"
      max_velocity: 5.0
      max_torque: 2.0
      
    joint7:
      node_id: 7
      operation_mode: "PPM"
      max_velocity: 5.0
      max_torque: 2.0